name: Deploy functions for Supabase

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase
      - name: Deploy functions
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy join-game --project-ref $SUPABASE_PROJECT_REF
          supabase functions deploy create-game --project-ref $SUPABASE_PROJECT_REF
          supabase functions deploy submit-game-turn --project-ref $SUPABASE_PROJECT_REF
